{% set dev_name = "sdsl-lite" %}
{% set fork = "vgteam" %}
{% set name = dev_name ~ "-" ~ fork %}  # package name
{% set version = "2.3.1" %}
{% set vcs_tag = "v" ~ version ~ "-" ~ fork %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cartoonist/{{ dev_name }}/releases/download/{{ vcs_tag }}/{{ dev_name }}-{{ vcs_tag }}.tar.bz2
  sha256: 5da65a1eb6c8af23bd5d79e86d9f4db17e035e178b416a688c1d6394740fbc00
  patches:
    - 00-fix_cmake.patch
    - 01-external_gtest.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - make  # [linux]
    - {{ compiler('cxx') }}

test:
  requires:
    - {{ compiler('cxx') }}
    - make  # [linux]
  source_files:
    - Make.helper
    - examples
  commands:
    - cd examples && make all LIB_DIR=$PREFIX/lib INC_DIR=$PREFIX/include

about:
  home: https://github.com/vgteam/sdsl-lite
  license: GPL-3.0-or-later
  license_family: GPL
  summary: 'The Succinct Data Structure Library (vgteam fork)'
  description: |
    This is vgteam's fork of the Succinct Data Structure Library (SDSL). As SDSL
    2 is no longer maintained, vgteam tools and libraries will depend on this
    until SDSL 3 is released.
  dev_url: https://github.com/vgteam/sdsl-lite
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'

extra:
  recipe-maintainers:
    - cartoonist
